baseURL = "http://example.org/"

# æ›´æ”¹ä½¿ç”¨ Hugo æ„å»ºç½‘ç«™æ—¶ä½¿ç”¨çš„é»˜è®¤ä¸»é¢˜
theme = "LoveIt"

# ç½‘ç«™æ ‡é¢˜
title = "Morris' Blogs"

# ç½‘ç«™è¯­è¨€, ä»…åœ¨è¿™é‡Œ CN å¤§å†™ ["en", "zh-CN", "fr", "pl", ...]
languageCode = "en"
# è¯­è¨€åç§° ["English", "ç®€ä½“ä¸­æ–‡", "FranÃ§ais", "Polski", ...]
languageName = "English"
# æ˜¯å¦åŒ…æ‹¬ä¸­æ—¥éŸ©æ–‡å­—
hasCJKLanguage = true

# è°·æ­Œåˆ†æä»£å· [UA-XXXXXXXX-X]
googleAnalytics = "G-33KRCT3PJL"

# æ˜¯å¦ä½¿ç”¨ robots.txt
enableRobotsTXT = true
# æ˜¯å¦ä½¿ç”¨ git ä¿¡æ¯
enableGitInfo = true
# æ˜¯å¦ä½¿ç”¨ emoji ä»£ç 
enableEmoji = true




# ä½œè€…é…ç½®
[author]
  name = "Morris"
  email = "morrishohoho@gmail.com"
  link = "https://github.com/MorrisHohoho"

# èœå•é…ç½®
[menu]
  [[menu.main]]
    weight = 1
    identifier = "posts"
    # ä½ å¯ä»¥åœ¨åç§° (å…è®¸ HTML æ ¼å¼) ä¹‹å‰æ·»åŠ å…¶ä»–ä¿¡æ¯, ä¾‹å¦‚å›¾æ ‡
    pre = "ğŸ“–"
    # ä½ å¯ä»¥åœ¨åç§° (å…è®¸ HTML æ ¼å¼) ä¹‹åæ·»åŠ å…¶ä»–ä¿¡æ¯, ä¾‹å¦‚å›¾æ ‡
    post = ""
    name = "Posts"
    url = "/posts/"
    # å½“ä½ å°†é¼ æ ‡æ‚¬åœåœ¨æ­¤èœå•é“¾æ¥ä¸Šæ—¶, å°†æ˜¾ç¤ºçš„æ ‡é¢˜
    title = ""
  [[menu.main]]
    weight = 2
    identifier = "tags"
    pre = "ğŸ”–"
    post = ""
    name = "Tags"
    url = "/tags/"
    title = ""
  [[menu.main]]
    weight = 3
    identifier = "categories"
    pre = "ğŸ—‚ï¸"
    post = ""
    name = "Categories"
    url = "/categories/"
    title = ""
  [[menu.main]]
    weight = 4
    identifier = "about"
    pre = "ğŸ¦–"
    post = ""
    name = "About"
    url = "/about/"
    title = ""

[params]
  # ç½‘ç«™é»˜è®¤ä¸»é¢˜æ ·å¼ ["auto", "light", "dark"]
  defaultTheme = "auto"
  # å…¬å…± git ä»“åº“è·¯å¾„ï¼Œä»…åœ¨ enableGitInfo è®¾ä¸º true æ—¶æœ‰æ•ˆ
  gitRepo = ""
  # LoveIt æ–°å¢ | 0.1.1 å“ªç§å“ˆå¸Œå‡½æ•°ç”¨æ¥ SRI, ä¸ºç©ºæ—¶è¡¨ç¤ºä¸ä½¿ç”¨ SRI
  # ["sha256", "sha384", "sha512", "md5"]
  fingerprint = ""
  # LoveIt æ–°å¢ | 0.2.0 æ—¥æœŸæ ¼å¼
  dateFormat = "2006-01-02"
  # ç½‘ç«™æ ‡é¢˜, ç”¨äº Open Graph å’Œ Twitter Cards
  title = "æˆ‘çš„ç½‘ç«™"
  # ç½‘ç«™æè¿°, ç”¨äº RSS, SEO, Open Graph å’Œ Twitter Cards
  description = "Morris' Blogs"
  # ç½‘ç«™å›¾ç‰‡, ç”¨äº Open Graph å’Œ Twitter Cards
  images = ["/logo.png"]


  # é¡µé¢å¤´éƒ¨å¯¼èˆªæ é…ç½®
  [params.header]
    # æ¡Œé¢ç«¯å¯¼èˆªæ æ¨¡å¼ ["fixed", "normal", "auto"]
    desktopMode = "fixed"
    # ç§»åŠ¨ç«¯å¯¼èˆªæ æ¨¡å¼ ["fixed", "normal", "auto"]
    mobileMode = "auto"
    # LoveIt æ–°å¢ | 0.2.0 é¡µé¢å¤´éƒ¨å¯¼èˆªæ æ ‡é¢˜é…ç½®
    [params.header.title]
      # LOGO çš„ URL
      logo = "/images/favicon.png"
      # æ ‡é¢˜åç§°
      name = "Win! èµ¢!"
      # ä½ å¯ä»¥åœ¨åç§° (å…è®¸ HTML æ ¼å¼) ä¹‹å‰æ·»åŠ å…¶ä»–ä¿¡æ¯, ä¾‹å¦‚å›¾æ ‡
      pre = ""
      # ä½ å¯ä»¥åœ¨åç§° (å…è®¸ HTML æ ¼å¼) ä¹‹åæ·»åŠ å…¶ä»–ä¿¡æ¯, ä¾‹å¦‚å›¾æ ‡
      post = ""
      # LoveIt æ–°å¢ | 0.2.5 æ˜¯å¦ä¸ºæ ‡é¢˜æ˜¾ç¤ºæ‰“å­—æœºåŠ¨ç”»
      typeit = false

 # LoveIt æ–°å¢ | 0.2.0 æœç´¢é…ç½®
  [params.search]
    enable = true
    # æœç´¢å¼•æ“çš„ç±»å‹ ["lunr", "algolia"]
    type = "lunr"
    # æ–‡ç« å†…å®¹æœ€é•¿ç´¢å¼•é•¿åº¦
    contentLength = 4000
    # æœç´¢æ¡†çš„å ä½æç¤ºè¯­
    placeholder = ""
    # LoveIt æ–°å¢ | 0.2.1 æœ€å¤§ç»“æœæ•°ç›®
    maxResultLength = 10
    # LoveIt æ–°å¢ | 0.2.3 ç»“æœå†…å®¹ç‰‡æ®µé•¿åº¦
    snippetLength = 50
    # LoveIt æ–°å¢ | 0.2.1 æœç´¢ç»“æœä¸­é«˜äº®éƒ¨åˆ†çš„ HTML æ ‡ç­¾
    highlightTag = "em"
    # LoveIt æ–°å¢ | 0.2.4 æ˜¯å¦åœ¨æœç´¢ç´¢å¼•ä¸­ä½¿ç”¨åŸºäº baseURL çš„ç»å¯¹è·¯å¾„
    absoluteURL = false
    [params.search.algolia]
      index = ""
      appID = ""
      searchKey = ""

  # LoveIt æ–°å¢ | 0.2.0 åº”ç”¨å›¾æ ‡é…ç½®
  [params.app]
    # å½“æ·»åŠ åˆ° iOS ä¸»å±å¹•æˆ–è€… Android å¯åŠ¨å™¨æ—¶çš„æ ‡é¢˜, è¦†ç›–é»˜è®¤æ ‡é¢˜
    title = "Morris Win!"
    # æ˜¯å¦éšè—ç½‘ç«™å›¾æ ‡èµ„æºé“¾æ¥
    noFavicon = false
    # æ›´ç°ä»£çš„ SVG ç½‘ç«™å›¾æ ‡, å¯æ›¿ä»£æ—§çš„ .png å’Œ .ico æ–‡ä»¶
    svgFavicon = ""
    # Android æµè§ˆå™¨ä¸»é¢˜è‰²
    themeColor = "#ffffff"
    # Safari å›¾æ ‡é¢œè‰²
    iconColor = "#5bbad5"
    # Windows v8-10ç£è´´é¢œè‰²
    tileColor = "#da532c"

# Hugo è§£ææ–‡æ¡£çš„é…ç½®
[markup]
  # è¯­æ³•é«˜äº®è®¾ç½® (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false æ˜¯å¿…è¦çš„è®¾ç½® (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false

  # ä¸»é¡µé…ç½®
  [params.home]
    # LoveIt æ–°å¢ | 0.2.0 RSS æ–‡ç« æ•°ç›®
    rss = 10
    # ä¸»é¡µä¸ªäººä¿¡æ¯
    [params.home.profile]
      enable = true
      # Gravatar é‚®ç®±ï¼Œç”¨äºä¼˜å…ˆåœ¨ä¸»é¡µæ˜¾ç¤ºçš„å¤´åƒ
      gravatarEmail = ""
      # ä¸»é¡µæ˜¾ç¤ºå¤´åƒçš„ URL
      avatarURL = "images/avatar.jpg"
      # LoveIt æ›´æ”¹ | 0.2.7 ä¸»é¡µæ˜¾ç¤ºçš„ç½‘ç«™æ ‡é¢˜ (æ”¯æŒ HTML æ ¼å¼)
      title = "Morris' Blogs"
      # ä¸»é¡µæ˜¾ç¤ºçš„ç½‘ç«™å‰¯æ ‡é¢˜ (å…è®¸ HTML æ ¼å¼)
      subtitle = "Welcome! æ¬¢è¿å…‰ä¸´ï¼"
      # æ˜¯å¦ä¸ºå‰¯æ ‡é¢˜æ˜¾ç¤ºæ‰“å­—æœºåŠ¨ç”»
      typeit = true
      # æ˜¯å¦æ˜¾ç¤ºç¤¾äº¤è´¦å·
      social = true
      # LoveIt æ–°å¢ | 0.2.0 å…è´£å£°æ˜ (æ”¯æŒ HTML æ ¼å¼)
      disclaimer = "The avatar is generated by Stable Diffusion."
    # ä¸»é¡µæ–‡ç« åˆ—è¡¨
    [params.home.posts]
      enable = true
      # ä¸»é¡µæ¯é¡µæ˜¾ç¤ºæ–‡ç« æ•°é‡
      paginate = 6
      # LoveIt åˆ é™¤ | 0.2.0 è¢« params.page ä¸­çš„ hiddenFromHomePage æ›¿ä»£
      # å½“ä½ æ²¡æœ‰åœ¨æ–‡ç« å‰ç½®å‚æ•°ä¸­è®¾ç½® "hiddenFromHomePage" æ—¶çš„é»˜è®¤è¡Œä¸º
      defaultHiddenFromHomePage = false



# ä½œè€…çš„ç¤¾äº¤ä¿¡æ¯è®¾ç½®
  [params.social]
    GitHub = "MorrisHohoho"
    Email = "morrishohoho@gmail.com"
    RSS = true
